### PR TITLE
fix errors if the server somehow sends an empty json chat msg

### PR DESCRIPTION
**Pull request by 182exe**
some servers (minemen.club, specifically) have a weird thing where they will occasionally send a chat message packet that doesn't have anything in it.

just adding a ?? and setting it to an empty string if the json isn't there fixes this.

### CODE REVIEW

**Review by extremeheat — COMMENTED** [review]
How do you know this fixes anything, or is the right fix? It doesn't seem right.

**Comment by frej4189** [comment]
The constructor already handles empty messages properly. What error are you getting?

**Comment by IceTank** [comment]
I'm pretty sure `json` should be an object, not a string in this line. How does this not cause more issues than it solves?

**Comment by 182exe** [comment]
try joining minemen.club with a bot
its the only server i've seen do it, and it throws this:

L:\coding\bot309902093\node_modules\prismarine-chat\index.js:70
      if (typeof json.text === 'string' || typeof json.text === 'number') {
                      ^

TypeError: Cannot read properties of null (reading 'text')
    at ChatMessage.parse (L:\coding\bot309902093\node_modules\prismarine-chat\index.js:70:23)
    at new ChatMessage (L:\coding\bot309902093\node_modules\prismarine-chat\index.js:56:12)
    at Client.<anonymous> (L:\coding\bot309902093\node_modules\mineflayer\lib\plugins\entities.js:560:34)
    at Client.emit (node:events:520:28)
    at emitPacket (L:\coding\bot309902093\node_modules\minecraft-protocol\src\client.js:83:12)
    at FullPacketParser.<anonymous> (L:\coding\bot309902093\node_modules\minecraft-protocol\src\client.js:106:9)
    at FullPacketParser.emit (node:events:520:28)
    at addChunk (L:\coding\bot309902093\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:279:12)
    at readableAddChunk (L:\coding\bot309902093\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:262:11)
    at FullPacketParser.Readable.push (L:\coding\bot309902093\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:228:10)

but adding this just kinda makes it not do that
i just put an empty string but i guess it can be an object too..?

**Comment by IceTank** [comment]
I think this is caused by `MessageBuilder.fromString` returning `null` instead of an object. At least that's the only way I see `this.json` being `null`.

So the issue is somewhere in MessageBuilder

**Comment by IceTank** [comment]
Actually looking closer at the stack trace it looks like prismarine-chat failed to parse a custom player displayName. 

```text
at Client. (L:\coding\bot309902093\node_modules\mineflayer\lib\plugins\entities.js:560:34)
```

this line is responsible for converting the player_info packet displayName property to a chat message object. The server you are trying to join sends an invalid display name response. It should be sending a json string but is instead sending `'null'`. I don't know if this only happens with mineflayer bots or if this also happens when joining with a vanilla java client. If this would also crash a java client then I don't know if mineflayer should catch this. A work around to fix this is to ignore the invalid displayName by wrapping the display name parsing in a try catch block.

**Comment by 182exe** [comment]
would it be worth it to just add a catch block there? i feel like this isn't something only this server does, and it doesn't really feel like joining somewhere should crash stuff

**Comment by frej4189** [comment]
> would it be worth it to just add a catch block there? i feel like this isn't something only this server does, and it doesn't really feel like joining somewhere should crash stuff

We should focus on fixing the issue instead of ignoring its symptoms

**Comment by IceTank** [comment]
I think we need to fix it in Prismarine-chat. When prismarine-chat receives an invalid text message it should return null or an empty string. It does already throw errors in some places but I don't know if we want it to throw errors.

**Pull request closed without merging**
