### PR TITLE
Fixes 1.16 hex problems

### LINKED ISSUE #6: Add 1.16 hex color support
1.16 provides full rgb support with hex values.

An example chat component: `{ text: 'hello', color: '#00AAFF' }` which should render text as blue

### PR DESCRIPTION
**Pull request by KaffinPX**
closes #6 
pls unban me from prismarinejs lol

### CODE REVIEW

**Comment by rom1504** [comment]
idk what this does

**Comment by SiebeDW** [comment]
This is incorrect? You are parsing any hex as white. Best way to store this is probalby just the plain hex value.

**Comment by KaffinPX** [comment]
Got it fixed i think

**Comment by rom1504** [comment]
you still didn't say what it's supposed to do

**Comment by KaffinPX** [comment]
> you still didn't say what it's supposed to do

In 1.16 hex codes are added as colors, prismarine-chat was giving errors about cannot parse hex in debug mode, it adds support for hex codes by making color "custom" and color.toHex to hex code.

**Comment by rom1504** [comment]
I don't get it

maybe add a test case to make it clear that this is doing something we want ?

**Comment by rom1504** [comment]
old

**Pull request closed without merging**
