### PR TITLE
numbers need to be parsed too!

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by u9g** [comment]
this fixes that issue ^^^

**Comment by u9g** [comment]
not ready to be merged yet, using .toString doesn't parse the numbers

**Comment by u9g** [comment]
now it should be ready to be merged

**Comment by rom1504** [comment]
Should this really work ?
If there's a good reason, can you add a test to make sure it works ?

**Comment by u9g** [comment]
> Should this really work ?
> If there's a good reason, can you add a test to make sure it works ?

Yeah there is, in flying-squid, there are some chat messages that need to be from the language file. This is what they look like fully in text form: https://github.com/PrismarineJS/minecraft-data/blob/424c41d75e375c749640d608b9a3ae3c9592a25e/data/pc/1.16.1/language.json#L4148

**Comment by rom1504** [comment]
How is this related with number parsing ?

**Comment by u9g** [comment]
> How is this related with number parsing ?

the test that I just added fails without number parsing

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
