### PR TITLE
Introduce MessageBuilder

### PR DESCRIPTION
**Pull request by u9g**
Adds new MessageBuilder export that allows easy creation of ChatMessage's, for use in FlyingSquid or /tellraw ingame

### CODE REVIEW

**Comment by u9g** [comment]
Needs https://github.com/PrismarineJS/prismarine-nbt/pull/44 to be merged

**Comment by u9g** [comment]
should use https://github.com/PrismarineJS/prismarine-nbt/pull/48

**Comment by rom1504** [comment]
PrismarineJS/prismarine-nbt#48 landed, want to finish this ?

**Comment by u9g** [comment]
> [PrismarineJS/prismarine-nbt#48](https://github.com/PrismarineJS/prismarine-nbt/pull/48) landed, want to finish this ?

done

**Review by rom1504 — CHANGES_REQUESTED** [review]
looks good, can you add MessageBuilder to the readme ?

**Comment by builder-247** [comment]
Could you add a function to convert from motd to chatmessage or shall I open a PR once this has landed?

**Comment by u9g** [comment]
> looks good, can you add MessageBuilder to the readme ?

Added

> Could you add a function to convert from motd to chatmessage or shall I open a PR once this has landed?

Done

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
