### PR TITLE
add typings

### LINKED ISSUE #21: Add typings
Add typings for a ChatMessage Object

### PR DESCRIPTION
**Pull request by Gjum**
closes #21
closes PrismarineJS/mineflayer#2100

### CODE REVIEW

**Review by u9g — CHANGES_REQUESTED** [review]
can you also add types for MessageBuilder?

**Comment by u9g** [comment]
closes https://github.com/PrismarineJS/mineflayer/issues/2100

**Comment by Gjum** [comment]
I haven't used MessageBuilder myself so someone needs to check if they're all right. I've done my best based on the code though.

**Review by u9g — APPROVED** [review]
LGTM

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
